"""add loyalty program tables

Revision ID: b7a86f0c56d5
Revises: f25f9d19b5e6
Create Date: 2026-03-22 11:33:17.885353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a86f0c56d5'
down_revision: Union[str, Sequence[str], None] = 'f25f9d19b5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recompensas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('puntos_requeridos', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuentas_puntos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('saldo_puntos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_afiliacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id')
    )
    op.create_table('canjes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('recompensa_id', sa.Integer(), nullable=False),
    sa.Column('puntos_usados', sa.Integer(), nullable=False),
    sa.Column('fecha_canje', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_puntos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recompensa_id'], ['recompensas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_puntos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('monto_compra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_puntos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table("clientes", schema=None) as batch_op:
      batch_op.add_column(
          sa.Column("activo", sa.Boolean(), nullable=False, server_default=sa.true())
      )
      batch_op.add_column(
          sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"))
      )
      batch_op.add_column(
          sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"))
      )


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('activo')

    op.drop_table('movimientos_puntos')
    op.drop_table('canjes')
    op.drop_table('cuentas_puntos')
    op.drop_table('recompensas')
    # ### end Alembic commands ###
