"""add unique constraint to celular

Revision ID: f25f9d19b5e6
Revises: a81e058ed044
Create Date: 2026-03-21 12:01:50.974094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25f9d19b5e6'
down_revision: Union[str, Sequence[str], None] = 'a81e058ed044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clientes") as batch_op:
        batch_op.create_unique_constraint("uq_clientes_celular", ["celular"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clientes") as batch_op:
        batch_op.drop_constraint("uq_clientes_celular", type_="unique")
    # ### end Alembic commands ###
